

# Site settings
title: CSSclasses Materials
email: contact@cssconf.eu
description: "CSSclasses is for beginners and experts alike: Using CSS as a simple and low-barrier entry language, we empower people to understand their browser and to learn how to experiment with code. Workshop and hackathon in one event."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cssclass.es"
twitter_username: CSSclasses
github_username:  CSSclasses

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none

include:
  - .nojekyll
  - "js/cssclasses.min.js"
  - "js/cssclasses.min.js.map"

exclude:
  - "_sass/"
  - "bower.json"
  - "bower_components/"
  - "Gemfile"
  - "Gemfile.lock"
  - "gruntfile.js"
  - "node_modules/"
  - "package.json"
  - "README.md"
